name: biblebooks
description: A Dart library to get info about bible books.
version: 1.0.0
repository: https://github.com/MarkIvanDev/biblebooks_dart.git
issue_tracker: https://github.com/MarkIvanDev/biblebooks_dart/issues

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  slang: ^3.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
